server:
  host: "localhost"
  port: 8080

client:
  external:
    host: "localhost"
    port: 3001

  internal:
    path: "web/dist"
    userResource: false
    index: "index.html"

ssl:
  use: false
  keyStore: "$MYTH_KEY_STORE:keyStore.jks"
  keyAlias: "$MYTH_ALIAS:alias"
  keyStorePassword: "$MYTH_KEY_STORE_PASSWORD:key"
  port: "$MYTH_PORT:8081"

database:
  user: "mythscape"
  password: "mythscape"
  url: "jdbc:postgresql://localhost:5433/mythscape"

jwt:
  secret: "mythscape0123456789mythscape"
  issuer: "https://karcags.eu"
  audience: "https://karcags.eu"
  realm: "mythscape"
  expiration: 3600